// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xnco.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNco_CfgInitialize(XNco *InstancePtr, XNco_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u32 XNco_GetSine_sample_v(XNco *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco_ReadReg(InstancePtr->Axi4lites_BaseAddress, XNCO_AXI4LITES_ADDR_SINE_SAMPLE_V_DATA);
    return Data;
}

u32 XNco_GetSine_sample_vVld(XNco *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco_ReadReg(InstancePtr->Axi4lites_BaseAddress, XNCO_AXI4LITES_ADDR_SINE_SAMPLE_V_CTRL);
    return Data & 0x1;
}

void XNco_SetStep_size_v(XNco *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNco_WriteReg(InstancePtr->Axi4lites_BaseAddress, XNCO_AXI4LITES_ADDR_STEP_SIZE_V_DATA, Data);
}

u32 XNco_GetStep_size_v(XNco *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNco_ReadReg(InstancePtr->Axi4lites_BaseAddress, XNCO_AXI4LITES_ADDR_STEP_SIZE_V_DATA);
    return Data;
}

