// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXI4LiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Control signal of sine_sample_V
//        bit 0  - sine_sample_V_ap_vld (Read/COR)
//        others - reserved
// 0x14 : Data signal of sine_sample_V
//        bit 15~0 - sine_sample_V[15:0] (Read)
//        others   - reserved
// 0x18 : reserved
// 0x1c : Data signal of step_size_V
//        bit 15~0 - step_size_V[15:0] (Read/Write)
//        others   - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XNCO_AXI4LITES_ADDR_SINE_SAMPLE_V_CTRL 0x10
#define XNCO_AXI4LITES_ADDR_SINE_SAMPLE_V_DATA 0x14
#define XNCO_AXI4LITES_BITS_SINE_SAMPLE_V_DATA 16
#define XNCO_AXI4LITES_ADDR_STEP_SIZE_V_DATA   0x1c
#define XNCO_AXI4LITES_BITS_STEP_SIZE_V_DATA   16

