-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\lms\LMS_pkg.vhd
-- Created: 2013-10-28 11:39:56
-- 
-- Generated by MATLAB 8.1 and HDL Coder 3.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE LMS_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END LMS_pkg;

